@echo off
echo Starting TimeFlow Application...

echo 1. Starting Backend...
cd Back
start cmd /k "mvnw spring-boot:run"

echo 2. Starting Frontend...
cd ../Front
start cmd /k "npm install && npm run dev"

echo Done! Application is starting...