@echo off
echo Starting TimeFlow Application...

echo 1. Starting Backend...
cd Back
set JAVA_HOME=C:\Users\alien\.jdks\openjdk-26.0.1
start cmd /k "mvnw spring-boot:run"

echo 2. Starting Frontend...
cd ../Front
start cmd /k "npm install && npm run dev"

echo Done! Application is starting...